"""add table affiliation

Revision ID: 169f8093f4e5
Revises: 6366fab75026
Create Date: 2023-04-18 21:49:12.309942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169f8093f4e5'
down_revision = '6366fab75026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_affiliation', sa.String(length=100), nullable=False),
    sa.Column('nombre_utilisation', sa.Integer(), nullable=False),
    sa.Column('date_expiration', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation')
    # ### end Alembic commands ###
