"""create

Revision ID: 1d566a234d06
Revises: 
Create Date: 2023-04-09 08:13:40.626727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d566a234d06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_match', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('heure', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('coupons', sa.String(length=100), nullable=False),
    sa.Column('nombre_de_pieces', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_match', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('equipe1', sa.String(length=100), nullable=False),
    sa.Column('equipe2', sa.String(length=100), nullable=False),
    sa.Column('resultat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mes_grid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_match', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('equipe1', sa.String(length=100), nullable=False),
    sa.Column('equipe2', sa.String(length=100), nullable=False),
    sa.Column('resultat', sa.String(length=100), nullable=True),
    sa.Column('etat', sa.String(length=100), nullable=True),
    sa.Column('date_fin', sa.String(length=100), nullable=True),
    sa.Column('correct_resultat', sa.String(length=100), nullable=True),
    sa.Column('numero_grid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=True),
    sa.Column('prenom', sa.Text(), nullable=True),
    sa.Column('tel', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scores')
    op.drop_table('recipie')
    op.drop_table('mes_grid')
    op.drop_table('match')
    op.drop_table('coupons')
    op.drop_table('category')
    # ### end Alembic commands ###
