"""add table erreur 

Revision ID: 6366fab75026
Revises: 1d566a234d06
Create Date: 2023-04-17 16:48:26.106061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6366fab75026'
down_revision = '1d566a234d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erreur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('etat', sa.String(length=300), nullable=False),
    sa.Column('dateExpiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('dateExpiration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('dateExpiration',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))

    op.drop_table('erreur')
    # ### end Alembic commands ###
