"""add table

Revision ID: c732814d8c3c
Revises: f4897118be7e
Create Date: 2023-05-06 10:01:07.888949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c732814d8c3c'
down_revision = 'f4897118be7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexe', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_naissance', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_naissance')
        batch_op.drop_column('sexe')

    # ### end Alembic commands ###
