"""add table date_create 

Revision ID: c847fbe42812
Revises: 169f8093f4e5
Create Date: 2023-04-21 16:27:21.251621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c847fbe42812'
down_revision = '169f8093f4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))

    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    # ### end Alembic commands ###
