"""add table

Revision ID: f4897118be7e
Revises: 552ef6435a68
Create Date: 2023-05-01 15:52:36.393345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4897118be7e'
down_revision = '552ef6435a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gagnant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_match', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('etat', sa.String(length=100), nullable=False),
    sa.Column('numero_grid', sa.String(length=100), nullable=False),
    sa.Column('date_create', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gagnant')
    # ### end Alembic commands ###
